<?php

namespace common\models;


class Order extends \common\core\BaseActiveRecord
{
    public static function tableName()
    {
        return "{{%order}}";
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function getGame()
    {
        $name = $this->hasOne(Game::className(), ['id' => 'gameid'])->asArray();
        return $name;
    }

    public function getServer()
    {
        return $this->hasOne(Server::className(), ['id' => 'serverid'])->asArray();
    }
}