<?php
namespace api\modules\v1\controllers;


use api\controllers\BaseController;
use Yii;
use yii\filters\auth\QueryParamAuth;
/**
 * Class PersonalController
 * @package api\modules\v1\controllers
 * 需要验证token的访问请求
 */
class PersonalController extends BaseController
{
    private static $identity;
    public function init()
    {
        self::$identity=Yii::$app->user->getIdentity();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        /* 设置认证方式 */
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
        ];
        return $behaviors;
    }
    /**
     * @return array
     * 用户信息
     */
    public function actionInfo(){
        return UserController::Info();
    }

    /**
     * @return array
     * 游戏历史记录
     */
    public function actionGamehistory(){
        return UserController::Gamehistory();
    }

    /**
     * @return array
     * 我的订单信息
     */
    public function actionMyorder(){
        return UserController::Myorder();
    }
    /**
     * @return array
     * 玩游戏
     */
    public function actionPlay(){
        return ServerController::Play();
    }
    public function actionMygamerole($sid){
        return ServerController::MyGamerole($sid);
    }

}