<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/25
 * Time: 15:12
 */

namespace backend\models;

use common\helpers\ArrayHelper;
class PartnerUser extends \common\models\PartnerUsers
{
    public $ip,$api;
    public function afterFind()
    {
        $api_ip=json_decode($this->api_ip,true);
        if ($api_ip&& $api_ip['ip'])
            $this->ip=implode("\r\n",$api_ip['ip']);
        if ($api_ip&& $api_ip['api'])
            $this->api=implode("\r\n",$api_ip['api']);
        $this->password='';
        parent::afterFind();
    }
    public function beforeSave($insert)
    {
        $ip=$this->ip?explode("\r\n",$this->ip):[] ;
        $api=$this->api?explode("\r\n",$this->api):[];
        $this->api_ip=json_encode(['ip'=>$ip,'api'=>$api]);


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param $gid 剔除的Gid
     * @return array|\yii\db\ActiveRecord[]
     *
     */
    public function Gids($gid){
        $_where="partnerid = {$this->id}";
        if ($gid) $_where .= " and gid NOT in ({$gid})";
        $games=PartnerGame::find()->select('gid')->asArray()->where($_where)->all();
//        var_dump($games);
        $games=ArrayHelper::getColumn($games,'gid');
        return $games;
    }

    /**
     * @param $gid
     * @param string $sid 剔除的sid
     * @return array|\yii\db\ActiveRecord[]
     */
    public function Sids($gid,$sid=''){
        $_where="gid = {$gid} and pid = {$this->id}";
        if ($sid) $_where .= " and sid NOT in ({$sid})";
        $games=PartnerServer::find()->select('sid')->asArray()->where($_where)->all();
//        var_dump($games);
        $games=ArrayHelper::getColumn($games,'sid');
        return $games;
    }
}