<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/28
 * Time: 10:56
 */

namespace partner\models;


class Game extends \common\models\Game
{
//    /**
//     * @inheritdoc
//     */
//    public function behaviors()
//    {
//        return [
//            /**
//             * 写库和更新库时，时间自动完成
//             * 注意rules验证必填时可使用AttributeBehavior行为，model的EVENT_BEFORE_VALIDATE事件
//             */
//            'timestamp' => [
//                'class' => 'yii\behaviors\TimestampBehavior',
//                'createdAtAttribute' => 'addtime',
//                'updatedAtAttribute' => '',
//                'value' => time(),
//            ],
//        ];
//    }
    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
        $this->addtime=time();
    }
}